name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - 'assets/images/walter.jpg'
  - 'assets/images/kirbi.jpg'
  - 'assets/images/familia.jpeg'
  - 'assets/images/amigos.jpg'
  - 'assets/images/trabajo.jpg'
  - 'assets/images/viajes.jpg'
  - 'assets/images/sumar.png'
  - 'assets/images/niñoWither1.png'
  - 'assets/images/niñoWither2.png'
  - 'assets/images/niñoWither3.png'
  - 'assets/images/niñoWither4.png'
  - 'assets/images/niñoWither5.png'
  - 'assets/images/niñoWither6.png'
  - 'assets/images/niñoWither7.png'
  - 'assets/images/niñoWither8.png'
  - 'assets/images/niñoWither9.png'